// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5vP_prhdr8V8Z0dNLykZPJmfZvRLVz6k',
    appId: '1:1019480647858:android:907dc6866785c47ac3c1ab',
    messagingSenderId: '1019480647858',
    projectId: 'optitask-9ce02',
    databaseURL: 'https://optitask-9ce02-default-rtdb.firebaseio.com',
    storageBucket: 'optitask-9ce02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq97510ThdC8e-DTkgrUN2NO-7jr1aOmY',
    appId: '1:1019480647858:ios:d896fefac43b65bfc3c1ab',
    messagingSenderId: '1019480647858',
    projectId: 'optitask-9ce02',
    databaseURL: 'https://optitask-9ce02-default-rtdb.firebaseio.com',
    storageBucket: 'optitask-9ce02.appspot.com',
    iosClientId: '1019480647858-h94bh9478d2f4ql9ioqb1nnj6aet8std.apps.googleusercontent.com',
    iosBundleId: 'com.example.optitask',
  );
}
